ALTER TABLE "UserState" ADD COLUMN IF NOT EXISTS "name" TEXT;
ALTER TABLE "UserState" ADD COLUMN IF NOT EXISTS "age" INTEGER;
ALTER TABLE "UserState" ADD COLUMN IF NOT EXISTS "heightCm" DOUBLE PRECISION;
ALTER TABLE "UserState" ADD COLUMN IF NOT EXISTS "weightKg" DOUBLE PRECISION;
ALTER TABLE "UserState" ADD COLUMN IF NOT EXISTS "diagnosis" TEXT;
ALTER TABLE "UserState" ADD COLUMN IF NOT EXISTS "meds" TEXT;
ALTER TABLE "UserState" ADD COLUMN IF NOT EXISTS "fastingPeakMgDl" INTEGER;
ALTER TABLE "UserState" ADD COLUMN IF NOT EXISTS "postMealPeakMgDl" INTEGER;
ALTER TABLE "UserState" ADD COLUMN IF NOT EXISTS "wakeTime" TEXT;
ALTER TABLE "UserState" ADD COLUMN IF NOT EXISTS "onboardingDoneAt" TIMESTAMP(3);

CREATE INDEX IF NOT EXISTS "UserState_onboardingDoneAt_idx" ON "UserState"("onboardingDoneAt");